project:
  type: website
  output-dir: docs

website:
  title: "Nexus Lumina"
  favicon: ./images/nexus_lumina_icon.svg
  navbar:
    right:
      - icon: twitter
        href: https://x.com/@siggis13
      - icon: github
        href: https://github.com/siegfriedschaefer
  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "© Nexus Lumina 2024"
        href: index.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



